/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JLabel;
import kelas.Database;

/**
 *
 * @author Purnama Hardi Saputra
 */
public class Dashboard extends javax.swing.JFrame {
    private int x;
    private int y;
    /**
     * Creates new form Dashboard
     */
    // menampilkan data dari database saat kelas diakses
    public Dashboard() {
        initComponents();
        
        this.setLocationRelativeTo(null); // menengahkan screen
        this.setResizable(false); // mencegah bingkai berubah ukuran
        
        Database database = new Database();
        database.getDetail(this);
        database.getPending(this);
        database.getProgress(this);
        database.getSuccess(this);
    }
    
    // mengembalikan nilai jumlah income dalam bentuk JLabel
    public JLabel getIncome(){
        return this.incomeTxt;
    }
    
    // mengembalikan nilai jumlah order dalam bentuk JLabel
    public JLabel getOrder(){
        return this.orderTxt;
    }
    
    // mengembalikan nilai jumlah status yang pending dalam bentuk JLabel
    public JLabel getPending(){
        return this.pendingTxt;
    }
    
    // mengembalikan nilai jumlah status yang on progress dalam bentuk JLabel
    public JLabel getProgress(){
        return this.progressTxt;
    }
    
    // mengembalikan nilai jumlah status yang success dalam bentuk JLabel
    public JLabel getSuccess(){
        return this.successTxt;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pendingTxt = new javax.swing.JLabel();
        progressTxt = new javax.swing.JLabel();
        successTxt = new javax.swing.JLabel();
        orderTxt = new javax.swing.JLabel();
        incomeTxt = new javax.swing.JLabel();
        dashboardBtn = new javax.swing.JLabel();
        transactionBtn = new javax.swing.JLabel();
        inventoryBtn = new javax.swing.JLabel();
        trackingBtn = new javax.swing.JLabel();
        accountBtn = new javax.swing.JLabel();
        closeBtn = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JLabel();
        panel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pendingTxt.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pendingTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 70, 30));

        progressTxt.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(progressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 70, 30));

        successTxt.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(successTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 70, 30));

        orderTxt.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(orderTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 353, 200, 30));

        incomeTxt.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(incomeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 267, 200, 30));
        getContentPane().add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, 50));

        transactionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionBtnMouseClicked(evt);
            }
        });
        getContentPane().add(transactionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 180, 50));

        inventoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryBtnMouseClicked(evt);
            }
        });
        getContentPane().add(inventoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 150, 50));

        trackingBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trackingBtnMouseClicked(evt);
            }
        });
        getContentPane().add(trackingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 210, 50));

        accountBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountBtnMouseClicked(evt);
            }
        });
        getContentPane().add(accountBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 50, 50));

        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 3, 30, 30));

        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 3, 30, 30));

        panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard.png"))); // NOI18N
        panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMouseDragged(evt);
            }
        });
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMousePressed(evt);
            }
        });
        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transactionBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionBtnMouseClicked
        // mengarahkan ke halaman Transaction dan menghilangkan halaman ini
        Transaction transaction = new Transaction();
        transaction.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transactionBtnMouseClicked

    private void inventoryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryBtnMouseClicked
        // mengarahkan ke halaman Inventory dan menghilangkan halaman ini
        Inventory inventory = new Inventory();
        inventory.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_inventoryBtnMouseClicked

    private void trackingBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trackingBtnMouseClicked
        // mengarahkan ke halaman TrackingStatus dan menghilangkan halaman ini
        TrackingStatus trackingStatus = new TrackingStatus();
        trackingStatus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_trackingBtnMouseClicked

    private void accountBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountBtnMouseClicked
        // mengarahkan ke halaman Account dan menghilangkan halaman ini
        Account account = new Account();
        account.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accountBtnMouseClicked

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // menclose aplikasi
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        // meminimalkan tampilan aplikasi
        this.setExtendedState(Login.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMousePressed
        // mendapatkan lokasi x dan y dari screen
        this.x = evt.getX();
        this.y = evt.getY();
    }//GEN-LAST:event_panelMousePressed

    private void panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseDragged
        // untuk mengubah lokasi x dan y dari screen agar dapat digerakkan
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();
        
        this.setLocation(x1-x, y1-y);
    }//GEN-LAST:event_panelMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountBtn;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JLabel dashboardBtn;
    private javax.swing.JLabel incomeTxt;
    private javax.swing.JLabel inventoryBtn;
    private javax.swing.JLabel minimizeBtn;
    private javax.swing.JLabel orderTxt;
    private javax.swing.JLabel panel;
    private javax.swing.JLabel pendingTxt;
    private javax.swing.JLabel progressTxt;
    private javax.swing.JLabel successTxt;
    private javax.swing.JLabel trackingBtn;
    private javax.swing.JLabel transactionBtn;
    // End of variables declaration//GEN-END:variables
}
