/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import kelas.Database;
import kelas.Storage;

/**
 *
 * @author Purnama Hardi Saputra
 */
public class Inventory extends javax.swing.JFrame {
    private int x;
    private int y;
    private static DefaultTableModel table = new DefaultTableModel();
    /**
     * Creates new form Inventory
     */
    // menampilkan data dari database saat kelas diakses
    public Inventory() {
        initComponents();
        
        this.setLocationRelativeTo(null); // menengahkan screen
        this.setResizable(false); // mencegah bingkai berubah ukuran
        Database database = new Database();
        database.showTransaction(this);
    }
    
    // mensetting tabel yang ada dan menerima datanya dari kelas Storage
    public void setTable(Storage storage) {
        ArrayList<ArrayList<String>> dataString = storage.showDataString();
        String[] cobox = {"Pilih Kolom", "ID", "Customer", "Service", "Day", "Laundry", "Payment", "Items", "Price"};
        String[] column = {"ID", "Customer", "Service", "Day", "Laundry", "Payment", "Items", "Price"};
        
        table.setColumnCount(0);
        table.setRowCount(0);
        for(int i = 0; i < column.length; i++){
            table.addColumn(column[i]);
        }
        
        for(int i = 0; i < cobox.length; i++){
            searchCobox.addItem(cobox[i]);
            inputCobox.addItem(cobox[i]);
        }
        
        // Ambil data string
        int numColumns = dataString.size();
        int numRows = dataString.get(0).size(); // Anggap semua ArrayList memiliki ukuran yang sama
        for (int i = 0; i < numRows; i++) {
            Object[] row = new Object[numColumns + 2]; // Jumlah kolom tambahan untuk items dan price
            for (int j = 0; j < numColumns; j++) {
                row[j] = dataString.get(j).get(i);
            }
            // Memasukkan items dan price ke kolom terakhir
            row[numColumns] = storage.showDataDouble().get(0).get(i); // Items
            row[numColumns + 1] = storage.showDataDouble().get(1).get(i); // Price
            table.addRow(row);
        }
        
        inventoryTable.setModel(table);
    }
    
    // mengembalikan nilai combo box yang dipilih dalam bentuk index
    public int getIndex() {
        return searchCobox.getSelectedIndex() - 1;
    }
    
    // mengembalikan nilai combo box yang dipilih dalam bentuk index
    public int getColumn() {
        return inputCobox.getSelectedIndex();
    }
    
    // mencari data berdasarkan combo box yang dipilih
    private void filter(String query) {
        table = (DefaultTableModel) inventoryTable.getModel();
        TableRowSorter<DefaultTableModel> tr = new 
        TableRowSorter<DefaultTableModel> (table);
        
        inventoryTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query, getIndex()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inventoryTable = new javax.swing.JTable();
        deleteBtn = new javax.swing.JLabel();
        dashboardBtn = new javax.swing.JLabel();
        transactionBtn = new javax.swing.JLabel();
        inventoryBtn = new javax.swing.JLabel();
        trackingBtn = new javax.swing.JLabel();
        accountBtn = new javax.swing.JLabel();
        editBtn = new javax.swing.JLabel();
        closeBtn = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JLabel();
        searchCobox = new javax.swing.JComboBox<>();
        inputCobox = new javax.swing.JComboBox<>();
        inputTxt = new javax.swing.JTextField();
        searchTxt = new javax.swing.JTextField();
        panel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(inventoryTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 198, 640, 250));

        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 140, 50));

        dashboardBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardBtnMouseClicked(evt);
            }
        });
        getContentPane().add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, 50));

        transactionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionBtnMouseClicked(evt);
            }
        });
        getContentPane().add(transactionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 180, 50));
        getContentPane().add(inventoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 150, 50));

        trackingBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trackingBtnMouseClicked(evt);
            }
        });
        getContentPane().add(trackingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 210, 50));

        accountBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountBtnMouseClicked(evt);
            }
        });
        getContentPane().add(accountBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 50, 50));

        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });
        getContentPane().add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 140, 50));

        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 3, 30, 30));

        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 3, 30, 30));

        getContentPane().add(searchCobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 150, 30));

        getContentPane().add(inputCobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 150, 30));
        getContentPane().add(inputTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 150, 30));

        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtKeyReleased(evt);
            }
        });
        getContentPane().add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 150, 30));

        panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory.png"))); // NOI18N
        panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMouseDragged(evt);
            }
        });
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMousePressed(evt);
            }
        });
        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBtnMouseClicked
        // mengarahkan ke halaman Dashboard dan menghilangkan halaman ini
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardBtnMouseClicked

    private void transactionBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionBtnMouseClicked
        // mengarahkan ke halaman Transaksi dan menghilangkan halaman ini
        Transaction transaction = new Transaction();
        transaction.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transactionBtnMouseClicked

    private void trackingBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trackingBtnMouseClicked
        // mengarahkan ke halaman TrackingStatus dan menghilangkan halaman ini
        TrackingStatus trackingStatus = new TrackingStatus();
        trackingStatus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_trackingBtnMouseClicked

    private void accountBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountBtnMouseClicked
        // mengarahkan ke halaman Account dan menghilangkan halaman ini
        Account account = new Account();
        account.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accountBtnMouseClicked

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
        // mengedit data tabel yang diselect
        Database database = new Database();
        int row;
        String input, id, column;
        if(getColumn() != 0){
            row = inventoryTable.getSelectedRow();
            id = table.getValueAt(row, 0).toString();
            input = inputTxt.getText();
            column = inputCobox.getItemAt(getColumn());
            database.updateInventory(id, input, column);
            table.setValueAt(input, row, getColumn() - 1);
        } else {
            JOptionPane.showMessageDialog(null, "Choose Column in ComboBox", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editBtnMouseClicked

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        // menghapus data jika data tabel yang diselect berjumlah satu
        int[] selectedRows = inventoryTable.getSelectedRows();        
        Database databases = new Database();
        if(selectedRows.length == 1) {
            int row = inventoryTable.getSelectedRow();
            String id = table.getValueAt(row, 0).toString();
            table.removeRow(inventoryTable.getSelectedRow());
            databases.deleteInventory(id);
        } else if(selectedRows.length == 0) { 
            JOptionPane.showMessageDialog(null, "Harap Pilih Data Terlebih Dahulu");
        } else {
            JOptionPane.showMessageDialog(null, "Harap Delete Satu per Satu");
        }
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // menclose aplikasi
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        // meminimalkan tampilan aplikasi
        this.setExtendedState(Login.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMousePressed
        // mendapatkan lokasi x dan y dari screen
        this.x = evt.getX();
        this.y = evt.getY();
    }//GEN-LAST:event_panelMousePressed

    private void panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseDragged
        // untuk mengubah lokasi x dan y dari screen agar dapat digerakkan
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();
        
        this.setLocation(x1-x, y1-y);
    }//GEN-LAST:event_panelMouseDragged

    private void searchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyReleased
        // menjalankan pencarian pada textfield search
        String query = searchTxt.getText();
        
        filter(query);
    }//GEN-LAST:event_searchTxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountBtn;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JLabel dashboardBtn;
    private javax.swing.JLabel deleteBtn;
    private javax.swing.JLabel editBtn;
    private javax.swing.JComboBox<String> inputCobox;
    private javax.swing.JTextField inputTxt;
    private javax.swing.JLabel inventoryBtn;
    private javax.swing.JTable inventoryTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel minimizeBtn;
    private javax.swing.JLabel panel;
    private javax.swing.JComboBox<String> searchCobox;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JLabel trackingBtn;
    private javax.swing.JLabel transactionBtn;
    // End of variables declaration//GEN-END:variables
}
