/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import kelas.Result;

/**
 *
 * @author Purnama Hardi Saputra
 */
public class Invoice extends javax.swing.JFrame {
    private int x;
    private int y;
    Result result = new Result();
    private Transaction transaction;
    /**
     * Creates new form Invoice
     */
    // menampilkan invoice yang disetting di kelas Result berdasarkan data yang ada di kelas Transaksi
    public Invoice(Transaction transaction) {
        initComponents();
        
        this.setLocationRelativeTo(null); // menengahkan screen
        this.setResizable(false); // mencegah bingkai berubah ukuran
        
        result.generateInvoiceImage(transaction, this);
        
        this.transaction = transaction;
    }
    
    // mengembalikan nilai label invoice dalam bentuk JLabel
    public JLabel setInvoice(){
        return this.invoiceLabel;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardBtn = new javax.swing.JLabel();
        transactionBtn = new javax.swing.JLabel();
        inventoryBtn = new javax.swing.JLabel();
        trackingBtn = new javax.swing.JLabel();
        accountBtn = new javax.swing.JLabel();
        downloadBtn = new javax.swing.JLabel();
        closeBtn = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JLabel();
        invoiceLabel = new javax.swing.JLabel();
        panel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardBtnMouseClicked(evt);
            }
        });
        getContentPane().add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, 50));

        transactionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionBtnMouseClicked(evt);
            }
        });
        getContentPane().add(transactionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 180, 50));

        inventoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryBtnMouseClicked(evt);
            }
        });
        getContentPane().add(inventoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 150, 50));

        trackingBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trackingBtnMouseClicked(evt);
            }
        });
        getContentPane().add(trackingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 210, 50));

        accountBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountBtnMouseClicked(evt);
            }
        });
        getContentPane().add(accountBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 50, 50));

        downloadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                downloadBtnMouseClicked(evt);
            }
        });
        getContentPane().add(downloadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 472, 140, 50));

        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 3, 30, 30));

        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 3, 30, 30));

        invoiceLabel.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(invoiceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 270, 355));

        panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Invoice.png"))); // NOI18N
        panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMouseDragged(evt);
            }
        });
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMousePressed(evt);
            }
        });
        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // menclose aplikasi
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        // meminimalkan tampilan aplikasi
        this.setExtendedState(Login.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void dashboardBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBtnMouseClicked
        // mengarahkan ke halaman Dashboard dan menghilangkan halaman ini
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardBtnMouseClicked

    private void transactionBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionBtnMouseClicked
        // mengarahkan ke halaman Transaction dan menghilangkan halaman ini
        Transaction transaction = new Transaction();
        transaction.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transactionBtnMouseClicked

    private void inventoryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryBtnMouseClicked
        // mengarahkan ke halaman Inventory dan menghilangkan halaman ini
        Inventory inventory = new Inventory();
        inventory.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_inventoryBtnMouseClicked

    private void trackingBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trackingBtnMouseClicked
        // mengarahkan ke halaman TrackingStatus dan menghilangkan halaman ini
        TrackingStatus trackingStatus = new TrackingStatus();
        trackingStatus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_trackingBtnMouseClicked

    private void accountBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountBtnMouseClicked
        // mengarahkan ke halaman Account dan menghilangkan halaman ini
        Account account = new Account();
        account.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accountBtnMouseClicked

    private void downloadBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downloadBtnMouseClicked
        // mendownload image yang berada di kelas Result
        try {
            result.downloadImage(transaction);
        } catch (IOException ex) {
            Logger.getLogger(Invoice.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_downloadBtnMouseClicked

    private void panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMousePressed
        // mendapatkan lokasi x dan y dari screen
        this.x = evt.getX();
        this.y = evt.getY();
    }//GEN-LAST:event_panelMousePressed

    private void panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseDragged
        // untuk mengubah lokasi x dan y dari screen agar dapat digerakkan
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();
        
        this.setLocation(x1-x, y1-y);
    }//GEN-LAST:event_panelMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Transaction transaction = new Transaction();
                new Invoice(transaction).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountBtn;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JLabel dashboardBtn;
    private javax.swing.JLabel downloadBtn;
    private javax.swing.JLabel inventoryBtn;
    private javax.swing.JLabel invoiceLabel;
    private javax.swing.JLabel minimizeBtn;
    private javax.swing.JLabel panel;
    private javax.swing.JLabel trackingBtn;
    private javax.swing.JLabel transactionBtn;
    // End of variables declaration//GEN-END:variables
}
