/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import kelas.Database;

/**
 *
 * @author Purnama Hardi Saputra
 */
public class Login extends javax.swing.JFrame {
    private int x;
    private int y;
    private String username;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null); // menengahkan screen
        this.setResizable(false); // mencegah bingkai berubah ukuran
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordTxt = new javax.swing.JPasswordField();
        usernameTxt = new javax.swing.JTextField();
        enableBtn = new javax.swing.JLabel();
        disableBtn = new javax.swing.JLabel();
        closeBtn = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JLabel();
        loginBtn = new javax.swing.JLabel();
        registerBtn = new javax.swing.JLabel();
        panel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 304, 420, 61));

        usernameTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 196, 470, 61));

        enableBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enableBtnMouseClicked(evt);
            }
        });
        getContentPane().add(enableBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, 40, 50));

        disableBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableBtnMouseClicked(evt);
            }
        });
        getContentPane().add(disableBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, 40, 50));

        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 3, 30, 30));

        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 3, 30, 30));

        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 140, 50));

        registerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBtnMouseClicked(evt);
            }
        });
        getContentPane().add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 80, 30));

        panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login1.png"))); // NOI18N
        panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMouseDragged(evt);
            }
        });
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMousePressed(evt);
            }
        });
        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // menclose aplikasi
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        // meminimalkan tampilan aplikasi
        this.setExtendedState(Login.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void enableBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enableBtnMouseClicked
        // mengubah tampilan menjadi disable password dan memperlihatkan password
        disableBtn.setVisible(true);
        disableBtn.setEnabled(true);
        passwordTxt.setEchoChar((char)0);
        ImageIcon A= new ImageIcon(getClass().getResource
        ("/Login2.png"));
        panel.setIcon(A);
        enableBtn.setVisible(false);
        enableBtn.setEnabled(false);
    }//GEN-LAST:event_enableBtnMouseClicked

    private void disableBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableBtnMouseClicked
        // mengubah tampilan menjadi enable password dan menyembunyikan password
        enableBtn.setVisible(true);
        enableBtn.setEnabled(true);
        passwordTxt.setEchoChar((char)8226);
        ImageIcon A= new ImageIcon(getClass().getResource
        ("/Login1.png"));
        panel.setIcon(A);
        disableBtn.setVisible(false);
        disableBtn.setEnabled(false);
    }//GEN-LAST:event_disableBtnMouseClicked

    private void registerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseClicked
        // mengarahkan ke halaman Register
        Register register = new Register();
        register.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerBtnMouseClicked

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        // Mencocokkan username dan password yang di database dan ketika berhasil akan masuk ke Dashboard
        String username = usernameTxt.getText();
        String password = passwordTxt.getText();
        Database database = new Database();
        Transaction transaction = new Transaction();
        if (username != null && !username.isEmpty() && password != null && !password.isEmpty()) {
            database.showLogin(username, password);
        } else {
            JOptionPane.showMessageDialog(null, "Username and password are required.", "Error", JOptionPane.ERROR_MESSAGE);
        }        
        this.dispose();
    }//GEN-LAST:event_loginBtnMouseClicked

    private void panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMousePressed
        // mendapatkan lokasi x dan y dari screen
        this.x = evt.getX();
        this.y = evt.getY();
    }//GEN-LAST:event_panelMousePressed

    private void panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseDragged
        // untuk mengubah lokasi x dan y dari screen agar dapat digerakkan
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();
        
        this.setLocation(x1-x, y1-y);
    }//GEN-LAST:event_panelMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeBtn;
    private javax.swing.JLabel disableBtn;
    private javax.swing.JLabel enableBtn;
    private javax.swing.JLabel loginBtn;
    private javax.swing.JLabel minimizeBtn;
    private javax.swing.JLabel panel;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JLabel registerBtn;
    public static javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
