/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import kelas.Database;
import kelas.Tracking;



/**
 *
 * @author Purnama Hardi Saputra
 */
public class TrackingStatus extends javax.swing.JFrame {
    private int x;
    private int y;
    private static DefaultTableModel table = new DefaultTableModel();
    /**
     * Creates new form TrackingStatus
     */
    // menampilkan data dari database saat kelas diakses
    public TrackingStatus(){
        initComponents();
        
        this.setLocationRelativeTo(null); // menengahkan screen
        this.setResizable(false); // mencegah bingkai berubah ukuran
        
        Database database = new Database();
        database.showTransaction(this);
    }
    
    //mensetting tabel yang ada dan menerima datanya dari kelas Tracking
    public void setTable(Tracking tracking) {
        ArrayList<ArrayList<String>> dataString = tracking.showDataString();
        String[] cobox = {"Pilih Status", "Pending", "On Progress", "Success"};
        String[] column = {"ID", "Customer", "Service", "Day", "Laundry", "Payment", "Status", "Items", "Price"};
        
        table.setColumnCount(0);
        table.setRowCount(0);
        for(int i = 0; i < column.length; i++){
            table.addColumn(column[i]);
        }
        
        for(int i = 0; i < cobox.length; i++){
            statusCobox.addItem(cobox[i]);
        }
        
        // Ambil data string
        int numColumns = dataString.size();
        int numRows = dataString.get(0).size(); // Anggap semua ArrayList memiliki ukuran yang sama

        for (int i = 0; i < numRows; i++) {
            Object[] row = new Object[numColumns + 2]; // Jumlah kolom tambahan untuk items dan price
            for (int j = 0; j < numColumns; j++) {
                row[j] = dataString.get(j).get(i);
            }
            // Memasukkan items dan price ke kolom terakhir
            row[numColumns] = tracking.showDataDouble().get(0).get(i); // Items
            row[numColumns + 1] = tracking.showDataDouble().get(1).get(i); // Price
            table.addRow(row);
        }
        trackingTable.setModel(table);
    }
    
    // mengembalikan nilai combo box yang dipilih dalam bentuk index
    public int getStatus() {
        return statusCobox.getSelectedIndex();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        trackingTable = new javax.swing.JTable();
        statusCobox = new javax.swing.JComboBox<>();
        accountBtn = new javax.swing.JLabel();
        trackingBtn = new javax.swing.JLabel();
        inventoryBtn = new javax.swing.JLabel();
        transactionBtn = new javax.swing.JLabel();
        dashboardBtn = new javax.swing.JLabel();
        updateBtn = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JLabel();
        closeBtn = new javax.swing.JLabel();
        panel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        trackingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(trackingTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 175, 600, 270));

        getContentPane().add(statusCobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 250, 30));

        accountBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountBtnMouseClicked(evt);
            }
        });
        getContentPane().add(accountBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 50, 50));
        getContentPane().add(trackingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 210, 50));

        inventoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryBtnMouseClicked(evt);
            }
        });
        getContentPane().add(inventoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 150, 50));

        transactionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionBtnMouseClicked(evt);
            }
        });
        getContentPane().add(transactionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 180, 50));

        dashboardBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardBtnMouseClicked(evt);
            }
        });
        getContentPane().add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, 50));

        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
        });
        getContentPane().add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 472, 140, 50));

        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 3, 30, 30));

        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 3, 30, 30));

        panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tracking Status.png"))); // NOI18N
        panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMouseDragged(evt);
            }
        });
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMousePressed(evt);
            }
        });
        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // menclose aplikasi
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        // meminimalkan tampilan aplikasi
        this.setExtendedState(Login.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void dashboardBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBtnMouseClicked
        // mengarahkan ke halaman Dashboard dan menghilangkan halaman ini
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardBtnMouseClicked

    private void transactionBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionBtnMouseClicked
        // mengarahkan ke halaman Account dan menghilangkan halaman ini
        Transaction transaction = new Transaction();
        transaction.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transactionBtnMouseClicked

    private void inventoryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryBtnMouseClicked
        // mengarahkan ke halaman Inventory dan menghilangkan halaman ini
        Inventory inventory = new Inventory();
        inventory.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_inventoryBtnMouseClicked

    private void accountBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountBtnMouseClicked
        // mengarahkan ke halaman Account dan menghilangkan halaman ini
        Account account = new Account();
        account.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accountBtnMouseClicked

    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked
        // mengupdate nilai status pada tabel
        Database database = new Database();
        int row;
        String status, id;
        if(getStatus() != 0){
            row = trackingTable.getSelectedRow();
            id = table.getValueAt(row, 0).toString();
            status = statusCobox.getItemAt(getStatus());
            database.updateStatus(id, status);
            table.setValueAt(status, row, 6);
        } else {
            JOptionPane.showMessageDialog(null, "Choose Input in ComboBox", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateBtnMouseClicked

    private void panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMousePressed
        // mendapatkan lokasi x dan y dari screen
        this.x = evt.getX();
        this.y = evt.getY();
    }//GEN-LAST:event_panelMousePressed

    private void panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseDragged
        // untuk mengubah lokasi x dan y dari screen agar dapat digerakkan
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();
        
        this.setLocation(x1-x, y1-y);
    }//GEN-LAST:event_panelMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrackingStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrackingStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrackingStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrackingStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrackingStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountBtn;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JLabel dashboardBtn;
    private javax.swing.JLabel inventoryBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel minimizeBtn;
    private javax.swing.JLabel panel;
    private javax.swing.JComboBox<String> statusCobox;
    private javax.swing.JLabel trackingBtn;
    private javax.swing.JTable trackingTable;
    private javax.swing.JLabel transactionBtn;
    private javax.swing.JLabel updateBtn;
    // End of variables declaration//GEN-END:variables
}
